# Generated by Django 4.0.1 on 2022-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRTE', models.CharField(max_length=7)),
                ('image', models.ImageField(upload_to='poste')),
                ('libelle', models.CharField(max_length=100)),
                ('schemas_preferentiel', models.TextField(blank=True)),
                ('autre_particulariter', models.TextField(blank=True)),
            ],
        ),
    ]
