# Generated by Django 4.0.1 on 2022-01-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0002_protectionbarre'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='protectionBarre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.protectionbarre'),
        ),
        migrations.AlterField(
            model_name='protectionbarre',
            name='libelle',
            field=models.CharField(max_length=3),
        ),
    ]
