# Generated by Django 4.0.1 on 2022-01-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0003_poste_protectionbarre_alter_protectionbarre_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='idRTE',
            field=models.CharField(max_length=10),
        ),
    ]
