# Generated by Django 4.0.1 on 2022-01-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0004_alter_poste_idrte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatismePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Filerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='JDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={'ordering': ['libelle'], 'verbose_name': 'Poste'},
        ),
        migrations.AlterField(
            model_name='poste',
            name='libelle',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='poste',
            name='CCO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.cco'),
        ),
    ]
