# Generated by Django 4.0.1 on 2022-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0006_poste_automatismeposte_poste_filerie_poste_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.ImageField(blank=True, upload_to='poste'),
        ),
    ]
