# Generated by Django 4.0.1 on 2022-01-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0007_alter_poste_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='cco',
            name='libelle',
            field=models.CharField(max_length=1),
        ),
    ]
