# Generated by Django 4.0.1 on 2022-01-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0008_zone_alter_cco_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='image',
            field=models.ImageField(blank=True, upload_to='zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='presentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cco',
            name='libelle',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='impact',
            name='libelle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tension',
            name='libelle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='zone',
            name='libelle',
            field=models.CharField(max_length=20),
        ),
    ]
