# Generated by Django 4.0.1 on 2022-01-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0009_zone_image_zone_presentation_alter_cco_libelle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zone'},
        ),
        migrations.AddField(
            model_name='poste',
            name='Zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.zone'),
        ),
    ]
