# Generated by Django 4.0.1 on 2022-01-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0010_alter_zone_options_poste_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categorie Zone',
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='CategorieZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.categoriezone'),
        ),
    ]
