# Generated by Django 4.0.1 on 2022-01-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0011_categoriezone_zone_categoriezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriezone',
            options={'ordering': ['libelle'], 'verbose_name': 'Categorie Zone'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['libelle'], 'verbose_name': 'Zone'},
        ),
    ]
