# Generated by Django 4.0.1 on 2022-01-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0012_alter_categoriezone_options_alter_zone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='PO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.po'),
        ),
    ]
