# Generated by Django 4.0.1 on 2022-01-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0014_acr_alter_po_options_zone_acr'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'GMR',
                'ordering': ['libelle'],
            },
        ),
    ]
