# Generated by Django 4.0.1 on 2022-01-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0015_gmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='GMR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.gmr'),
        ),
    ]
