# Generated by Django 4.0.1 on 2022-01-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0016_zone_gmr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Groupement',
                'ordering': ['libelle'],
            },
        ),
    ]
