# Generated by Django 4.0.1 on 2022-01-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0017_groupement'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='Groupement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.groupement'),
        ),
    ]
