# Generated by Django 4.0.1 on 2022-01-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0018_poste_groupement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieConsigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categorie consigne',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Consigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('pdf', models.FileField(blank=True, upload_to='consigne')),
                ('url', models.URLField(blank=True)),
                ('CategorieConsigne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.categorieconsigne')),
            ],
            options={
                'verbose_name': 'Consigne',
                'ordering': ['libelle'],
            },
        ),
    ]
