# Generated by Django 4.0.1 on 2022-01-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0019_categorieconsigne_consigne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieconsigne',
            name='libelle',
            field=models.CharField(max_length=40),
        ),
    ]
