# Generated by Django 4.0.1 on 2022-01-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0020_alter_categorieconsigne_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Type Client',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('TypeClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.typeclient')),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['libelle'],
            },
        ),
    ]
