# Generated by Django 4.0.1 on 2022-01-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0023_client_gmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Poste',
            field=models.ManyToManyField(to='poste.Poste'),
        ),
    ]
