# Generated by Django 4.0.1 on 2022-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0025_zone_groupement'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='Consigne',
            field=models.ManyToManyField(to='poste.Consigne'),
        ),
    ]
