# Generated by Django 4.0.1 on 2022-01-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0026_poste_consigne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='protectionBarre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.protectionbarre'),
        ),
    ]
