# Generated by Django 4.0.1 on 2022-01-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0029_alter_poste_consigne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poste',
            options={'ordering': ['libelle'], 'verbose_name': 'Poste électrique'},
        ),
        migrations.AlterField(
            model_name='poste',
            name='AutomatismePoste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.automatismeposte', verbose_name='AUTOMATISME POSTE'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='Groupement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.groupement', verbose_name='GROUPEMENT'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='Impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.impact', verbose_name='IMPACT'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='JDB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.jdb', verbose_name='CLIENTS RACCORDÉS SUR JDB'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='Zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.zone', verbose_name='ZONE'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='protectionBarre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.protectionbarre', verbose_name='PROTECTIONS BARRES'),
        ),
    ]
