# Generated by Django 4.0.1 on 2022-01-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0030_alter_poste_options_alter_poste_automatismeposte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poste',
            options={'ordering': ['libelle'], 'verbose_name': 'POSTE ÉLECTRIQUE'},
        ),
    ]
