# Generated by Django 4.0.1 on 2022-01-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0035_alter_formation_maintenupar_alter_formation_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='Actualite',
            field=models.TextField(verbose_name='Actualité'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='Fonctionnement',
            field=models.TextField(verbose_name='Fonctionnement du maintien en compétence'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='MaintenuPar',
            field=models.CharField(max_length=50, verbose_name='Maintenu Par'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='PMC',
            field=models.TextField(verbose_name='Participez au maintien competénce du Centre Exploitation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='Titre',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
