# Generated by Django 4.0.1 on 2022-01-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0038_remove_consigne_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='Contenu',
            field=models.TextField(max_length=10),
        ),
    ]
