# Generated by Django 4.0.1 on 2022-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0042_alter_categorieconsigne_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieconsigne',
            name='libelle',
            field=models.URLField(max_length=400),
        ),
    ]
