# Generated by Django 4.0.1 on 2022-02-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0044_alter_consigne_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Titre', models.CharField(max_length=30)),
                ('Contenu', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='theme',
            name='Theme',
            field=models.CharField(max_length=50, verbose_name='Thème'),
        ),
    ]
