# Generated by Django 4.0.1 on 2022-02-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0045_commentaire_alter_theme_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='Poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.poste', verbose_name='POSTE'),
        ),
    ]
