# Generated by Django 4.0.1 on 2022-02-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0046_commentaire_poste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['Date']},
        ),
    ]
