# Generated by Django 4.0.1 on 2022-03-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0048_alter_commentaire_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fiche',
        ),
        migrations.DeleteModel(
            name='TypeFiche',
        ),
    ]
