# Generated by Django 4.0.1 on 2022-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0050_alter_zone_gmr_alter_zone_groupement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='ACR',
        ),
        migrations.AddField(
            model_name='zone',
            name='ACR',
            field=models.ManyToManyField(to='poste.ACR'),
        ),
    ]
