# Generated by Django 4.0.1 on 2022-03-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0053_alter_categorieconsigne_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieconsigne',
            name='libelle',
            field=models.URLField(max_length=50),
        ),
    ]
