# Generated by Django 4.0.1 on 2022-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0054_alter_categorieconsigne_libelle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consigne',
            options={'ordering': ['libelle'], 'verbose_name': 'CONSIGNE'},
        ),
    ]
