# Generated by Django 4.0.1 on 2022-03-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0055_alter_consigne_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['libelle'], 'verbose_name': 'CLIENTS RACCORDÉS SUR JDB'},
        ),
    ]
