# Generated by Django 4.0.1 on 2022-03-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0056_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['libelle'], 'verbose_name': 'Clients raccordés sur JDB'},
        ),
        migrations.AlterModelOptions(
            name='consigne',
            options={'ordering': ['libelle'], 'verbose_name': 'Consignes'},
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={'ordering': ['libelle'], 'verbose_name': 'Poste électrique', 'verbose_name_plural': 'Postes électriques'},
        ),
    ]
