# Generated by Django 4.0.1 on 2022-03-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0057_alter_client_options_alter_consigne_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consigne',
            options={'ordering': ['libelle'], 'verbose_name': 'Consigne'},
        ),
    ]
