# Generated by Django 4.0.1 on 2022-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0058_alter_consigne_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Titre',
            field=models.CharField(max_length=80),
        ),
    ]
