# Generated by Django 4.0.1 on 2022-03-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0061_commentaire_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Statut',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.statut'),
        ),
    ]
