# Generated by Django 4.0.1 on 2022-03-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0063_typeposte_poste_typeposte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Filerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.filerie', verbose_name='FILERIE'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='Tension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.tension', verbose_name='TENSION'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='TypePoste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.typeposte', verbose_name='TYPE'),
        ),
        migrations.RemoveField(
            model_name='poste',
            name='Zone',
        ),
        migrations.AddField(
            model_name='poste',
            name='Zone',
            field=models.ManyToManyField(blank=True, to='poste.Zone', verbose_name='ZONE'),
        ),
    ]
