# Generated by Django 4.0.1 on 2022-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0064_alter_poste_filerie_alter_poste_tension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Consigne',
            field=models.ManyToManyField(blank=True, to='poste.Consigne', verbose_name='CONSIGNE'),
        ),
    ]
