# Generated by Django 4.0.1 on 2022-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0066_alter_poste_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='Zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='Poste',
            field=models.ManyToManyField(blank=True, to='poste.Poste'),
        ),
    ]
