# Generated by Django 4.0.1 on 2022-04-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0067_remove_poste_zone_zone_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='Poste',
            field=models.ManyToManyField(blank=True, related_name='poste', to='poste.Poste'),
        ),
    ]
