# Generated by Django 4.0.1 on 2022-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0068_alter_zone_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='statut_ap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poste',
            name='statut_sp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Poste',
            field=models.ManyToManyField(blank=True, to='poste.Poste'),
        ),
    ]
