# Generated by Django 4.0.1 on 2022-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0070_alter_poste_statut_ap_alter_poste_statut_sp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='statut_ap',
            field=models.BooleanField(default=False, verbose_name='ÉTAT : AUTRE PARTICULARITER'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='statut_sp',
            field=models.BooleanField(default=False, verbose_name='ÉTAT : SCHEMAS PREFERENTIEL'),
        ),
    ]
