# Generated by Django 4.0.1 on 2022-04-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0075_commentairehistorique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentaireHistorique',
        ),
    ]
