# Generated by Django 4.0.1 on 2022-04-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0076_delete_commentairehistorique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Titre', models.CharField(max_length=80)),
                ('Contenu', models.TextField()),
                ('Action', models.CharField(max_length=15)),
                ('Version', models.BigIntegerField()),
                ('Poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.poste', verbose_name='POSTE')),
                ('Statut', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.statut')),
                ('idOriginal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.commentaire')),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
    ]
