# Generated by Django 4.0.1 on 2022-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0077_commentairehistorique'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairehistorique',
            name='DateAction',
            field=models.DateTimeField(null=True),
        ),
    ]
