# Generated by Django 4.0.1 on 2022-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0085_alter_protectionbarre_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tension',
            name='libelle',
            field=models.CharField(max_length=20),
        ),
    ]
