# Generated by Django 4.0.1 on 2022-04-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0086_alter_tension_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairehistorique',
            name='Action',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='commentairehistorique',
            name='Version',
            field=models.BigIntegerField(blank=True),
        ),
    ]
