# Generated by Django 4.0.1 on 2022-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0088_alter_commentairehistorique_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairehistorique',
            name='Version',
            field=models.BigIntegerField(default=0),
        ),
    ]
