# Generated by Django 4.0.1 on 2022-04-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0089_alter_commentairehistorique_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairehistorique',
            name='Version',
        ),
    ]
