# Generated by Django 4.0.1 on 2022-04-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0091_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentairehistorique',
            options={'ordering': ['-DateAction']},
        ),
    ]
