# Generated by Django 4.0.1 on 2022-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0092_alter_commentairehistorique_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairehistorique',
            name='idOriginal',
            field=models.IntegerField(),
        ),
    ]
