# Generated by Django 4.0.1 on 2022-04-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0093_alter_commentairehistorique_idoriginal'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='Historique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.commentairehistorique'),
        ),
    ]
