# Generated by Django 4.0.1 on 2022-04-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0096_prioriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='Prioriter',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.prioriter'),
        ),
    ]
