# Generated by Django 4.0.1 on 2022-04-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0097_commentaire_prioriter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='Prioriter',
        ),
    ]
