# Generated by Django 4.0.1 on 2022-05-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0101_commentaire_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairehistorique',
            name='Zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.zone', verbose_name='ZONE'),
        ),
    ]
