# Generated by Django 4.0.1 on 2022-05-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0103_alter_commentaire_fiche_alter_commentaire_poste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='Fiche',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='Zone',
        ),
    ]
