# Generated by Django 4.0.1 on 2022-05-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0104_remove_commentaire_fiche_remove_commentaire_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairehistorique',
            name='Zone',
        ),
    ]
