# Generated by Django 4.0.1 on 2022-05-11 12:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0105_remove_commentairehistorique_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='schemas_preferentiel',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
