# Generated by Django 4.0.1 on 2022-05-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0107_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='Prenom',
        ),
    ]
