# Generated by Django 3.1 on 2022-06-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0110_auto_20220607_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propriete',
            options={'ordering': ['libelle']},
        ),
    ]
