# Generated by Django 3.1 on 2022-06-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0111_auto_20220607_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Propriete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.propriete', verbose_name='PROPRIÉTÉ'),
        ),
    ]
