# Generated by Django 3.1 on 2022-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0112_auto_20220607_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectionbarre',
            name='libelle',
            field=models.CharField(max_length=15),
        ),
    ]
