# Generated by Django 3.1 on 2022-06-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0113_auto_20220607_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='poste',
            name='Couleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.couleur', verbose_name='Couleur'),
        ),
    ]
