# Generated by Django 3.1 on 2022-06-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0114_auto_20220615_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Couleur',
            field=models.ForeignKey(choices=[('1', 'BLEU'), ('2', 'ROUGE'), ('3', 'NOIR')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.couleur', verbose_name='Couleur'),
        ),
    ]
