# Generated by Django 3.1 on 2022-06-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0115_auto_20220615_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='libelle',
            field=models.CharField(max_length=35),
        ),
    ]
