# Generated by Django 3.1 on 2022-06-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0116_auto_20220616_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='Couleur',
        ),
        migrations.DeleteModel(
            name='Couleur',
        ),
    ]
