# Generated by Django 3.1 on 2022-06-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0117_auto_20220616_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.impact', verbose_name='IMPACTE'),
        ),
    ]
