# Generated by Django 3.1 on 2022-06-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0118_auto_20220622_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEtrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AlterField(
            model_name='poste',
            name='Impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.impact', verbose_name='IMPACT'),
        ),
        migrations.AddField(
            model_name='poste',
            name='TypeEtrange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.typeetrange', verbose_name='TYPE'),
        ),
    ]
