# Generated by Django 3.1 on 2022-06-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0120_auto_20220622_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='autre_particulariter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
