# Generated by Django 3.1 on 2022-06-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0121_auto_20220622_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='statut_ap',
            field=models.BooleanField(default=False, null=True, verbose_name='VÉRIFIER : AUTRE PARTICULARITER'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='statut_sp',
            field=models.BooleanField(default=False, null=True, verbose_name='VÉRIFIER : SCHEMAS PREFERENTIEL'),
        ),
    ]
