# Generated by Django 3.1 on 2022-06-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0122_auto_20220622_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='Propriete',
        ),
        migrations.DeleteModel(
            name='Propriete',
        ),
    ]
