# Generated by Django 4.0.1 on 2022-03-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0051_remove_zone_acr_zone_acr'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poste.zone'),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
