# Generated by Django 4.0.1 on 2022-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_alter_commentaire_zone_delete_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-DateCreation']},
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='Date',
            new_name='DateModification',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='DateCreation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
