# Generated by Django 4.0.1 on 2022-04-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0099_delete_prioriter'),
        ('zone', '0003_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='Statut',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StatutZone', to='poste.statut'),
        ),
    ]
