# Generated by Django 4.0.1 on 2022-05-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0104_remove_commentaire_fiche_remove_commentaire_zone'),
        ('zone', '0004_commentaire_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Titre', models.CharField(max_length=80)),
                ('Contenu', models.TextField()),
                ('idOriginal', models.IntegerField()),
                ('Action', models.CharField(blank=True, max_length=20)),
                ('DateAction', models.DateTimeField(auto_now=True, null=True)),
                ('Statut', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Statut', to='poste.statut')),
                ('Zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ZONE', to='poste.zone')),
            ],
            options={
                'ordering': ['-DateAction'],
            },
        ),
    ]
