# Generated by Django 4.0.1 on 2022-05-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0005_commentairehistorique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='Prenom',
        ),
        migrations.RemoveField(
            model_name='commentairehistorique',
            name='Prenom',
        ),
    ]
