# Generated by Django 4.0.1 on 2022-05-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('lien', models.CharField(max_length=50)),
                ('nomButton', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Doc',
                'ordering': ['libelle'],
            },
        ),
    ]
