# Generated by Django 4.0.1 on 2022-05-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='lien',
            field=models.URLField(max_length=600),
        ),
    ]
