# Generated by Django 4.0.1 on 2022-05-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_rename_lien_doc_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=600)),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Doc',
                'ordering': ['libelle'],
            },
        ),
    ]
