# Generated by Django 4.0.1 on 2022-05-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_lien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lien',
            options={'ordering': ['Titre'], 'verbose_name': 'Lien utile'},
        ),
        migrations.RenameField(
            model_name='lien',
            old_name='libelle',
            new_name='Titre',
        ),
    ]
