# Generated by Django 4.0.1 on 2022-03-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=20)),
                ('Contenu', models.TextField()),
                ('TypeFiche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.typefiche')),
            ],
        ),
    ]
