# Generated by Django 4.0.1 on 2022-03-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='image',
            field=models.ImageField(blank=True, upload_to='themes'),
        ),
    ]
