# Generated by Django 4.0.1 on 2022-03-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_fiche_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Titre', models.CharField(max_length=30)),
                ('Contenu', models.TextField()),
                ('Fiche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.fiche', verbose_name='FICHE')),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
    ]
