# Generated by Django 4.0.1 on 2022-03-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_alter_fiche_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Fiche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Theme_Fiche', to='theme.fiche', verbose_name='FICHE'),
        ),
    ]
