# Generated by Django 4.0.1 on 2022-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_alter_commentaire_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='image',
            field=models.ImageField(blank=True, upload_to='themes-modop'),
        ),
    ]
