# Generated by Django 4.0.1 on 2022-05-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0105_remove_commentairehistorique_zone'),
        ('theme', '0006_alter_fiche_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-DateCreation']},
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='Date',
            new_name='DateModification',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='DateCreation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='Statut',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Statut_TH', to='poste.statut'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='Fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.fiche', verbose_name='FICHE'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='Nom',
            field=models.CharField(max_length=55, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='Prenom',
            field=models.CharField(max_length=55, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='Titre',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='CommentaireHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Titre', models.CharField(max_length=80)),
                ('Contenu', models.TextField()),
                ('idOriginal', models.IntegerField()),
                ('Action', models.CharField(blank=True, max_length=20)),
                ('DateAction', models.DateTimeField(auto_now=True, null=True)),
                ('Fiche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.fiche', verbose_name='FICHE')),
                ('Statut', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Statut_TC', to='poste.statut')),
            ],
            options={
                'ordering': ['-DateAction'],
            },
        ),
    ]
