# Generated by Django 4.0.1 on 2022-05-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='Prenom',
        ),
        migrations.RemoveField(
            model_name='commentairehistorique',
            name='Prenom',
        ),
    ]
